### ISSUE TITLE
how to use persian OCR

### ISSUE THREAD

**Issue by taghilooniya** [HamidRezaAttar/Persian-OCR-Streamlit#1]
Hi Hamid reza, i will use your code. I run it but it had'nt a result for me. can you explain steps of using it? should I only run scan and OCR file?

**Comment by HamidRezaAttar** [comment]
Hi @taghilooniya 
Did you check live demo? 
For getting correct output you should: 
* First Scan Your Image Using Scan Page
* Second Extract Text From Your Scanned Image Using OCR Page

I'll add a notebook for full use case besides this streamlit demo. 
Thanks for your feedback.

**Comment by taghilooniya** [comment]
by clicking on demo i get this error. You do not have access to this app or it does not exist...
I used scan and OCR page but it didn't worked for me! I would be appreciate if you add the notebook. thank you

**Comment by taghilooniya** [comment]
Hi. By cliching on demo I get this error. You do mot have access to this
app or it doese not exist... I would be appreciate if you put that
notebook. Thank you
